version: "3"

services:
  spark-iceberg:
    image: spark-iceberg:3.1.3_0.12.1
    volumes:
      - ./warehouse:/home/iceberg/warehouse
      - ./notebooks:/home/iceberg/notebooks/notebooks
    ports:
      - 8888:8888
      - 8080:8080
      - 18080:18080
